// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: driver/driver.proto

package driver

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Messages
type Driver struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName     string                 `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"firstName,omitempty"`
	LastName      string                 `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"lastName,omitempty"`
	Plate         string                 `protobuf:"bytes,4,opt,name=plate,proto3" json:"plate,omitempty"`
	TaxiType      string                 `protobuf:"bytes,5,opt,name=taxi_type,json=taxiType,proto3" json:"taxiType,omitempty"`
	CarBrand      string                 `protobuf:"bytes,6,opt,name=car_brand,json=carBrand,proto3" json:"carBrand,omitempty"`
	CarModel      string                 `protobuf:"bytes,7,opt,name=car_model,json=carModel,proto3" json:"carModel,omitempty"`
	Latitude      float64                `protobuf:"fixed64,8,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,9,opt,name=longitude,proto3" json:"longitude,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Driver) Reset() {
	*x = Driver{}
	mi := &file_driver_driver_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Driver) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Driver) ProtoMessage() {}

func (x *Driver) ProtoReflect() protoreflect.Message {
	mi := &file_driver_driver_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Driver.ProtoReflect.Descriptor instead.
func (*Driver) Descriptor() ([]byte, []int) {
	return file_driver_driver_proto_rawDescGZIP(), []int{0}
}

func (x *Driver) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Driver) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *Driver) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *Driver) GetPlate() string {
	if x != nil {
		return x.Plate
	}
	return ""
}

func (x *Driver) GetTaxiType() string {
	if x != nil {
		return x.TaxiType
	}
	return ""
}

func (x *Driver) GetCarBrand() string {
	if x != nil {
		return x.CarBrand
	}
	return ""
}

func (x *Driver) GetCarModel() string {
	if x != nil {
		return x.CarModel
	}
	return ""
}

func (x *Driver) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Driver) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *Driver) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Driver) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type AddDriverRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FirstName     string                 `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Plate         string                 `protobuf:"bytes,3,opt,name=plate,proto3" json:"plate,omitempty"`
	TaxiType      string                 `protobuf:"bytes,4,opt,name=taxi_type,json=taxiType,proto3" json:"taxi_type,omitempty"`
	CarModel      string                 `protobuf:"bytes,5,opt,name=car_model,json=carModel,proto3" json:"car_model,omitempty"`
	CarBrand      string                 `protobuf:"bytes,6,opt,name=car_brand,json=carBrand,proto3" json:"car_brand,omitempty"`
	Latitude      float64                `protobuf:"fixed64,7,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,8,opt,name=longitude,proto3" json:"longitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddDriverRequest) Reset() {
	*x = AddDriverRequest{}
	mi := &file_driver_driver_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddDriverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddDriverRequest) ProtoMessage() {}

func (x *AddDriverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_driver_driver_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddDriverRequest.ProtoReflect.Descriptor instead.
func (*AddDriverRequest) Descriptor() ([]byte, []int) {
	return file_driver_driver_proto_rawDescGZIP(), []int{1}
}

func (x *AddDriverRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *AddDriverRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *AddDriverRequest) GetPlate() string {
	if x != nil {
		return x.Plate
	}
	return ""
}

func (x *AddDriverRequest) GetTaxiType() string {
	if x != nil {
		return x.TaxiType
	}
	return ""
}

func (x *AddDriverRequest) GetCarModel() string {
	if x != nil {
		return x.CarModel
	}
	return ""
}

func (x *AddDriverRequest) GetCarBrand() string {
	if x != nil {
		return x.CarBrand
	}
	return ""
}

func (x *AddDriverRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *AddDriverRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type AddDriverResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddDriverResponse) Reset() {
	*x = AddDriverResponse{}
	mi := &file_driver_driver_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddDriverResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddDriverResponse) ProtoMessage() {}

func (x *AddDriverResponse) ProtoReflect() protoreflect.Message {
	mi := &file_driver_driver_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddDriverResponse.ProtoReflect.Descriptor instead.
func (*AddDriverResponse) Descriptor() ([]byte, []int) {
	return file_driver_driver_proto_rawDescGZIP(), []int{2}
}

func (x *AddDriverResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateDriverRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName     *string                `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3,oneof" json:"first_name,omitempty"`
	LastName      *string                `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3,oneof" json:"last_name,omitempty"`
	Plate         *string                `protobuf:"bytes,4,opt,name=plate,proto3,oneof" json:"plate,omitempty"`
	TaxiType      *string                `protobuf:"bytes,5,opt,name=taxi_type,json=taxiType,proto3,oneof" json:"taxi_type,omitempty"`
	CarModel      *string                `protobuf:"bytes,6,opt,name=car_model,json=carModel,proto3,oneof" json:"car_model,omitempty"`
	CarBrand      *string                `protobuf:"bytes,7,opt,name=car_brand,json=carBrand,proto3,oneof" json:"car_brand,omitempty"`
	Latitude      *float64               `protobuf:"fixed64,8,opt,name=latitude,proto3,oneof" json:"latitude,omitempty"`
	Longitude     *float64               `protobuf:"fixed64,9,opt,name=longitude,proto3,oneof" json:"longitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDriverRequest) Reset() {
	*x = UpdateDriverRequest{}
	mi := &file_driver_driver_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDriverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDriverRequest) ProtoMessage() {}

func (x *UpdateDriverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_driver_driver_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDriverRequest.ProtoReflect.Descriptor instead.
func (*UpdateDriverRequest) Descriptor() ([]byte, []int) {
	return file_driver_driver_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateDriverRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateDriverRequest) GetFirstName() string {
	if x != nil && x.FirstName != nil {
		return *x.FirstName
	}
	return ""
}

func (x *UpdateDriverRequest) GetLastName() string {
	if x != nil && x.LastName != nil {
		return *x.LastName
	}
	return ""
}

func (x *UpdateDriverRequest) GetPlate() string {
	if x != nil && x.Plate != nil {
		return *x.Plate
	}
	return ""
}

func (x *UpdateDriverRequest) GetTaxiType() string {
	if x != nil && x.TaxiType != nil {
		return *x.TaxiType
	}
	return ""
}

func (x *UpdateDriverRequest) GetCarModel() string {
	if x != nil && x.CarModel != nil {
		return *x.CarModel
	}
	return ""
}

func (x *UpdateDriverRequest) GetCarBrand() string {
	if x != nil && x.CarBrand != nil {
		return *x.CarBrand
	}
	return ""
}

func (x *UpdateDriverRequest) GetLatitude() float64 {
	if x != nil && x.Latitude != nil {
		return *x.Latitude
	}
	return 0
}

func (x *UpdateDriverRequest) GetLongitude() float64 {
	if x != nil && x.Longitude != nil {
		return *x.Longitude
	}
	return 0
}

type UpdateDriverResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDriverResponse) Reset() {
	*x = UpdateDriverResponse{}
	mi := &file_driver_driver_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDriverResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDriverResponse) ProtoMessage() {}

func (x *UpdateDriverResponse) ProtoReflect() protoreflect.Message {
	mi := &file_driver_driver_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDriverResponse.ProtoReflect.Descriptor instead.
func (*UpdateDriverResponse) Descriptor() ([]byte, []int) {
	return file_driver_driver_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateDriverResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetDriversRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"pageSize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDriversRequest) Reset() {
	*x = GetDriversRequest{}
	mi := &file_driver_driver_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDriversRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDriversRequest) ProtoMessage() {}

func (x *GetDriversRequest) ProtoReflect() protoreflect.Message {
	mi := &file_driver_driver_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDriversRequest.ProtoReflect.Descriptor instead.
func (*GetDriversRequest) Descriptor() ([]byte, []int) {
	return file_driver_driver_proto_rawDescGZIP(), []int{5}
}

func (x *GetDriversRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetDriversRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type PaginationMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"pageSize,omitempty"`
	TotalCount    int64                  `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"totalCount,omitempty"`
	TotalPages    int64                  `protobuf:"varint,4,opt,name=total_pages,json=totalPages,proto3" json:"totalPages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaginationMetadata) Reset() {
	*x = PaginationMetadata{}
	mi := &file_driver_driver_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaginationMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginationMetadata) ProtoMessage() {}

func (x *PaginationMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_driver_driver_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginationMetadata.ProtoReflect.Descriptor instead.
func (*PaginationMetadata) Descriptor() ([]byte, []int) {
	return file_driver_driver_proto_rawDescGZIP(), []int{6}
}

func (x *PaginationMetadata) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PaginationMetadata) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *PaginationMetadata) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *PaginationMetadata) GetTotalPages() int64 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

type GetDriversResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Drivers       []*Driver              `protobuf:"bytes,1,rep,name=drivers,proto3" json:"drivers,omitempty"`
	Meta          *PaginationMetadata    `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDriversResponse) Reset() {
	*x = GetDriversResponse{}
	mi := &file_driver_driver_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDriversResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDriversResponse) ProtoMessage() {}

func (x *GetDriversResponse) ProtoReflect() protoreflect.Message {
	mi := &file_driver_driver_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDriversResponse.ProtoReflect.Descriptor instead.
func (*GetDriversResponse) Descriptor() ([]byte, []int) {
	return file_driver_driver_proto_rawDescGZIP(), []int{7}
}

func (x *GetDriversResponse) GetDrivers() []*Driver {
	if x != nil {
		return x.Drivers
	}
	return nil
}

func (x *GetDriversResponse) GetMeta() *PaginationMetadata {
	if x != nil {
		return x.Meta
	}
	return nil
}

type GetNearbyDriversRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latitude      float64                `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	TaxiType      string                 `protobuf:"bytes,3,opt,name=taxi_type,json=taxiType,proto3" json:"taxi_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNearbyDriversRequest) Reset() {
	*x = GetNearbyDriversRequest{}
	mi := &file_driver_driver_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNearbyDriversRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNearbyDriversRequest) ProtoMessage() {}

func (x *GetNearbyDriversRequest) ProtoReflect() protoreflect.Message {
	mi := &file_driver_driver_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNearbyDriversRequest.ProtoReflect.Descriptor instead.
func (*GetNearbyDriversRequest) Descriptor() ([]byte, []int) {
	return file_driver_driver_proto_rawDescGZIP(), []int{8}
}

func (x *GetNearbyDriversRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *GetNearbyDriversRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *GetNearbyDriversRequest) GetTaxiType() string {
	if x != nil {
		return x.TaxiType
	}
	return ""
}

type NearbyDriver struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FirstName     string                 `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"firstName,omitempty"`
	LastName      string                 `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"lastName,omitempty"`
	Plate         string                 `protobuf:"bytes,3,opt,name=plate,proto3" json:"plate,omitempty"`
	DistanceKm    float64                `protobuf:"fixed64,4,opt,name=distance_km,json=distanceKm,proto3" json:"distanceKm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NearbyDriver) Reset() {
	*x = NearbyDriver{}
	mi := &file_driver_driver_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NearbyDriver) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NearbyDriver) ProtoMessage() {}

func (x *NearbyDriver) ProtoReflect() protoreflect.Message {
	mi := &file_driver_driver_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NearbyDriver.ProtoReflect.Descriptor instead.
func (*NearbyDriver) Descriptor() ([]byte, []int) {
	return file_driver_driver_proto_rawDescGZIP(), []int{9}
}

func (x *NearbyDriver) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *NearbyDriver) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *NearbyDriver) GetPlate() string {
	if x != nil {
		return x.Plate
	}
	return ""
}

func (x *NearbyDriver) GetDistanceKm() float64 {
	if x != nil {
		return x.DistanceKm
	}
	return 0
}

type GetNearbyDriversResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Drivers       []*NearbyDriver        `protobuf:"bytes,1,rep,name=drivers,proto3" json:"drivers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNearbyDriversResponse) Reset() {
	*x = GetNearbyDriversResponse{}
	mi := &file_driver_driver_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNearbyDriversResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNearbyDriversResponse) ProtoMessage() {}

func (x *GetNearbyDriversResponse) ProtoReflect() protoreflect.Message {
	mi := &file_driver_driver_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNearbyDriversResponse.ProtoReflect.Descriptor instead.
func (*GetNearbyDriversResponse) Descriptor() ([]byte, []int) {
	return file_driver_driver_proto_rawDescGZIP(), []int{10}
}

func (x *GetNearbyDriversResponse) GetDrivers() []*NearbyDriver {
	if x != nil {
		return x.Drivers
	}
	return nil
}

var File_driver_driver_proto protoreflect.FileDescriptor

const file_driver_driver_proto_rawDesc = "" +
	"\n" +
	"\x13driver/driver.proto\x12\x06driver\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf1\x02\n" +
	"\x06Driver\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x03 \x01(\tR\blastName\x12\x14\n" +
	"\x05plate\x18\x04 \x01(\tR\x05plate\x12\x1b\n" +
	"\ttaxi_type\x18\x05 \x01(\tR\btaxiType\x12\x1b\n" +
	"\tcar_brand\x18\x06 \x01(\tR\bcarBrand\x12\x1b\n" +
	"\tcar_model\x18\a \x01(\tR\bcarModel\x12\x1a\n" +
	"\blatitude\x18\b \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\t \x01(\x01R\tlongitude\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xf5\x01\n" +
	"\x10AddDriverRequest\x12\x1d\n" +
	"\n" +
	"first_name\x18\x01 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x02 \x01(\tR\blastName\x12\x14\n" +
	"\x05plate\x18\x03 \x01(\tR\x05plate\x12\x1b\n" +
	"\ttaxi_type\x18\x04 \x01(\tR\btaxiType\x12\x1b\n" +
	"\tcar_model\x18\x05 \x01(\tR\bcarModel\x12\x1b\n" +
	"\tcar_brand\x18\x06 \x01(\tR\bcarBrand\x12\x1a\n" +
	"\blatitude\x18\a \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\b \x01(\x01R\tlongitude\"#\n" +
	"\x11AddDriverResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x9c\x03\n" +
	"\x13UpdateDriverRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\"\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tH\x00R\tfirstName\x88\x01\x01\x12 \n" +
	"\tlast_name\x18\x03 \x01(\tH\x01R\blastName\x88\x01\x01\x12\x19\n" +
	"\x05plate\x18\x04 \x01(\tH\x02R\x05plate\x88\x01\x01\x12 \n" +
	"\ttaxi_type\x18\x05 \x01(\tH\x03R\btaxiType\x88\x01\x01\x12 \n" +
	"\tcar_model\x18\x06 \x01(\tH\x04R\bcarModel\x88\x01\x01\x12 \n" +
	"\tcar_brand\x18\a \x01(\tH\x05R\bcarBrand\x88\x01\x01\x12\x1f\n" +
	"\blatitude\x18\b \x01(\x01H\x06R\blatitude\x88\x01\x01\x12!\n" +
	"\tlongitude\x18\t \x01(\x01H\aR\tlongitude\x88\x01\x01B\r\n" +
	"\v_first_nameB\f\n" +
	"\n" +
	"_last_nameB\b\n" +
	"\x06_plateB\f\n" +
	"\n" +
	"_taxi_typeB\f\n" +
	"\n" +
	"_car_modelB\f\n" +
	"\n" +
	"_car_brandB\v\n" +
	"\t_latitudeB\f\n" +
	"\n" +
	"_longitude\"0\n" +
	"\x14UpdateDriverResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"D\n" +
	"\x11GetDriversRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"\x87\x01\n" +
	"\x12PaginationMetadata\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x03R\n" +
	"totalCount\x12\x1f\n" +
	"\vtotal_pages\x18\x04 \x01(\x03R\n" +
	"totalPages\"n\n" +
	"\x12GetDriversResponse\x12(\n" +
	"\adrivers\x18\x01 \x03(\v2\x0e.driver.DriverR\adrivers\x12.\n" +
	"\x04meta\x18\x02 \x01(\v2\x1a.driver.PaginationMetadataR\x04meta\"p\n" +
	"\x17GetNearbyDriversRequest\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x01R\tlongitude\x12\x1b\n" +
	"\ttaxi_type\x18\x03 \x01(\tR\btaxiType\"\x81\x01\n" +
	"\fNearbyDriver\x12\x1d\n" +
	"\n" +
	"first_name\x18\x01 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x02 \x01(\tR\blastName\x12\x14\n" +
	"\x05plate\x18\x03 \x01(\tR\x05plate\x12\x1f\n" +
	"\vdistance_km\x18\x04 \x01(\x01R\n" +
	"distanceKm\"J\n" +
	"\x18GetNearbyDriversResponse\x12.\n" +
	"\adrivers\x18\x01 \x03(\v2\x14.driver.NearbyDriverR\adrivers2\xb8\x02\n" +
	"\rDriverService\x12@\n" +
	"\tAddDriver\x12\x18.driver.AddDriverRequest\x1a\x19.driver.AddDriverResponse\x12I\n" +
	"\fUpdateDriver\x12\x1b.driver.UpdateDriverRequest\x1a\x1c.driver.UpdateDriverResponse\x12C\n" +
	"\n" +
	"GetDrivers\x12\x19.driver.GetDriversRequest\x1a\x1a.driver.GetDriversResponse\x12U\n" +
	"\x10GetNearbyDrivers\x12\x1f.driver.GetNearbyDriversRequest\x1a .driver.GetNearbyDriversResponseB8Z6github.com/AkifhanIlgaz/taxihub/common/genproto/driverb\x06proto3"

var (
	file_driver_driver_proto_rawDescOnce sync.Once
	file_driver_driver_proto_rawDescData []byte
)

func file_driver_driver_proto_rawDescGZIP() []byte {
	file_driver_driver_proto_rawDescOnce.Do(func() {
		file_driver_driver_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_driver_driver_proto_rawDesc), len(file_driver_driver_proto_rawDesc)))
	})
	return file_driver_driver_proto_rawDescData
}

var file_driver_driver_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_driver_driver_proto_goTypes = []any{
	(*Driver)(nil),                   // 0: driver.Driver
	(*AddDriverRequest)(nil),         // 1: driver.AddDriverRequest
	(*AddDriverResponse)(nil),        // 2: driver.AddDriverResponse
	(*UpdateDriverRequest)(nil),      // 3: driver.UpdateDriverRequest
	(*UpdateDriverResponse)(nil),     // 4: driver.UpdateDriverResponse
	(*GetDriversRequest)(nil),        // 5: driver.GetDriversRequest
	(*PaginationMetadata)(nil),       // 6: driver.PaginationMetadata
	(*GetDriversResponse)(nil),       // 7: driver.GetDriversResponse
	(*GetNearbyDriversRequest)(nil),  // 8: driver.GetNearbyDriversRequest
	(*NearbyDriver)(nil),             // 9: driver.NearbyDriver
	(*GetNearbyDriversResponse)(nil), // 10: driver.GetNearbyDriversResponse
	(*timestamppb.Timestamp)(nil),    // 11: google.protobuf.Timestamp
}
var file_driver_driver_proto_depIdxs = []int32{
	11, // 0: driver.Driver.created_at:type_name -> google.protobuf.Timestamp
	11, // 1: driver.Driver.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: driver.GetDriversResponse.drivers:type_name -> driver.Driver
	6,  // 3: driver.GetDriversResponse.meta:type_name -> driver.PaginationMetadata
	9,  // 4: driver.GetNearbyDriversResponse.drivers:type_name -> driver.NearbyDriver
	1,  // 5: driver.DriverService.AddDriver:input_type -> driver.AddDriverRequest
	3,  // 6: driver.DriverService.UpdateDriver:input_type -> driver.UpdateDriverRequest
	5,  // 7: driver.DriverService.GetDrivers:input_type -> driver.GetDriversRequest
	8,  // 8: driver.DriverService.GetNearbyDrivers:input_type -> driver.GetNearbyDriversRequest
	2,  // 9: driver.DriverService.AddDriver:output_type -> driver.AddDriverResponse
	4,  // 10: driver.DriverService.UpdateDriver:output_type -> driver.UpdateDriverResponse
	7,  // 11: driver.DriverService.GetDrivers:output_type -> driver.GetDriversResponse
	10, // 12: driver.DriverService.GetNearbyDrivers:output_type -> driver.GetNearbyDriversResponse
	9,  // [9:13] is the sub-list for method output_type
	5,  // [5:9] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_driver_driver_proto_init() }
func file_driver_driver_proto_init() {
	if File_driver_driver_proto != nil {
		return
	}
	file_driver_driver_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_driver_driver_proto_rawDesc), len(file_driver_driver_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_driver_driver_proto_goTypes,
		DependencyIndexes: file_driver_driver_proto_depIdxs,
		MessageInfos:      file_driver_driver_proto_msgTypes,
	}.Build()
	File_driver_driver_proto = out.File
	file_driver_driver_proto_goTypes = nil
	file_driver_driver_proto_depIdxs = nil
}
